name: 🐍 Contribution Snake

on:
  # Run daily at midnight UTC (adjust to your preference)
  schedule:
    - cron: '0 0 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Generate snake SVG
        uses: platane/snk@v1
        with:
          # Path where the SVG will be written
          file: output/github-contribution-grid-snake.svg

      - name: Commit updated SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "chore: update contribution snake" || echo "No changes to commit"
          git push
